name: Client CI/CD

on:
  push:
    branches: [ '**' ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      working-directory: ./client
      run: npm install

    - name: Lint
      working-directory: ./client
      run: npm run lint

    - name: Run tests
      working-directory: ./client
      run: npm test
      # This assumes you have a test script in your package.json

    - name: Build
      working-directory: ./client
      run: npm run build
      # Builds your application, make sure you have a build script in your package.json
  
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1

    # - name: Vercel Deploy
    #   uses: amondnet/vercel-action@v20
    #   with:
    #     vercel_token: ${{ secrets.VERCEL_TOKEN }}
    #     project_name: "group-project-team-7"
    #     org_id: ${{ secrets.VERCEL_ORG_ID }}
    #     project_id: ${{ secrets.VERCEL_PROJECT_ID }}
